INSERT INTO country(country,continent) VALUES ('Afghanistan',2);
INSERT INTO country(country,continent) VALUES ('Albania',1);
INSERT INTO country(country,continent) VALUES ('Algeria',3);
INSERT INTO country(country,continent) VALUES ('American Samoa',4);
INSERT INTO country(country,continent) VALUES ('Andorra',1);
INSERT INTO country(country,continent) VALUES ('Angola',3);
INSERT INTO country(country,continent) VALUES ('Anguilla',5);
INSERT INTO country(country,continent) VALUES (7,7);
INSERT INTO country(country,continent) VALUES ('Antigua and Barbuda',5);
INSERT INTO country(country,continent) VALUES ('Argentina',6);
INSERT INTO country(country,continent) VALUES ('Armenia',2);
INSERT INTO country(country,continent) VALUES ('Aruba',5);
INSERT INTO country(country,continent) VALUES ('Australia',4);
INSERT INTO country(country,continent) VALUES ('Austria',1);
INSERT INTO country(country,continent) VALUES ('Azerbaijan',2);
INSERT INTO country(country,continent) VALUES ('Bahamas',5);
INSERT INTO country(country,continent) VALUES ('Bahrain',2);
INSERT INTO country(country,continent) VALUES ('Bangladesh',2);
INSERT INTO country(country,continent) VALUES ('Barbados',5);
INSERT INTO country(country,continent) VALUES ('Belarus',1);
INSERT INTO country(country,continent) VALUES ('Belgium',1);
INSERT INTO country(country,continent) VALUES ('Belize',5);
INSERT INTO country(country,continent) VALUES ('Benin',3);
INSERT INTO country(country,continent) VALUES ('Bermuda',5);
INSERT INTO country(country,continent) VALUES ('Bhutan',2);
INSERT INTO country(country,continent) VALUES ('Bolivia',6);
INSERT INTO country(country,continent) VALUES ('Bosnia and Herzegovina',1);
INSERT INTO country(country,continent) VALUES ('Botswana',3);
INSERT INTO country(country,continent) VALUES ('Bouvet Island',7);
INSERT INTO country(country,continent) VALUES ('Brazil',6);
INSERT INTO country(country,continent) VALUES ('British Indian Ocean Territory',3);
INSERT INTO country(country,continent) VALUES ('Brunei',2);
INSERT INTO country(country,continent) VALUES ('Bulgaria',1);
INSERT INTO country(country,continent) VALUES ('Burkina Faso',3);
INSERT INTO country(country,continent) VALUES ('Burundi',3);
INSERT INTO country(country,continent) VALUES ('Cambodia',2);
INSERT INTO country(country,continent) VALUES ('Cameroon',3);
INSERT INTO country(country,continent) VALUES ('Canada',5);
INSERT INTO country(country,continent) VALUES ('Cape Verde',3);
INSERT INTO country(country,continent) VALUES ('Cayman Islands',5);
INSERT INTO country(country,continent) VALUES ('Central African Republic',3);
INSERT INTO country(country,continent) VALUES ('Chad',3);
INSERT INTO country(country,continent) VALUES ('Chile',6);
INSERT INTO country(country,continent) VALUES ('China',2);
INSERT INTO country(country,continent) VALUES ('Christmas Island',4);
INSERT INTO country(country,continent) VALUES ('Cocos (Keeling) Islands',4);
INSERT INTO country(country,continent) VALUES ('Colombia',6);
INSERT INTO country(country,continent) VALUES ('Comoros',3);
INSERT INTO country(country,continent) VALUES ('Congo',3);
INSERT INTO country(country,continent) VALUES ('Cook Islands',4);
INSERT INTO country(country,continent) VALUES ('Costa Rica',5);
INSERT INTO country(country,continent) VALUES ('Croatia',1);
INSERT INTO country(country,continent) VALUES ('Cuba',5);
INSERT INTO country(country,continent) VALUES ('Cyprus',2);
INSERT INTO country(country,continent) VALUES ('Czech Republic',1);
INSERT INTO country(country,continent) VALUES ('Denmark',1);
INSERT INTO country(country,continent) VALUES ('Djibouti',3);
INSERT INTO country(country,continent) VALUES ('Dominica',5);
INSERT INTO country(country,continent) VALUES ('Dominican Republic',5);
INSERT INTO country(country,continent) VALUES ('East Timor',2);
INSERT INTO country(country,continent) VALUES ('Ecuador',6);
INSERT INTO country(country,continent) VALUES ('Egypt',3);
INSERT INTO country(country,continent) VALUES ('El Salvador',5);
INSERT INTO country(country,continent) VALUES ('England',1);
INSERT INTO country(country,continent) VALUES ('Equatorial Guinea',3);
INSERT INTO country(country,continent) VALUES ('Eritrea',3);
INSERT INTO country(country,continent) VALUES ('Estonia',1);
INSERT INTO country(country,continent) VALUES ('Ethiopia',3);
INSERT INTO country(country,continent) VALUES ('Falkland Islands',6);
INSERT INTO country(country,continent) VALUES ('Faroe Islands',1);
INSERT INTO country(country,continent) VALUES ('Fiji Islands',4);
INSERT INTO country(country,continent) VALUES ('Finland',1);
INSERT INTO country(country,continent) VALUES ('France',1);
INSERT INTO country(country,continent) VALUES ('French Guiana',6);
INSERT INTO country(country,continent) VALUES ('French Polynesia',4);
INSERT INTO country(country,continent) VALUES ('French Southern territories',7);
INSERT INTO country(country,continent) VALUES ('Gabon',3);
INSERT INTO country(country,continent) VALUES ('Gambia',3);
INSERT INTO country(country,continent) VALUES ('Georgia',2);
INSERT INTO country(country,continent) VALUES ('Germany',1);
INSERT INTO country(country,continent) VALUES ('Ghana',3);
INSERT INTO country(country,continent) VALUES ('Gibraltar',1);
INSERT INTO country(country,continent) VALUES ('Greece',1);
INSERT INTO country(country,continent) VALUES ('Greenland',5);
INSERT INTO country(country,continent) VALUES ('Grenada',5);
INSERT INTO country(country,continent) VALUES ('Guadeloupe',5);
INSERT INTO country(country,continent) VALUES ('Guam',4);
INSERT INTO country(country,continent) VALUES ('Guatemala',5);
INSERT INTO country(country,continent) VALUES ('Guinea',3);
INSERT INTO country(country,continent) VALUES ('Guinea-Bissau',3);
INSERT INTO country(country,continent) VALUES ('Guyana',6);
INSERT INTO country(country,continent) VALUES ('Haiti',5);
INSERT INTO country(country,continent) VALUES ('Heard Island and McDonald Islands',7);
INSERT INTO country(country,continent) VALUES ('Holy See (Vatican City State)',1);
INSERT INTO country(country,continent) VALUES ('Honduras',5);
INSERT INTO country(country,continent) VALUES ('Hong Kong',2);
INSERT INTO country(country,continent) VALUES ('Hungary',1);
INSERT INTO country(country,continent) VALUES ('Iceland',1);
INSERT INTO country(country,continent) VALUES ('India',2);
INSERT INTO country(country,continent) VALUES ('Indonesia',2);
INSERT INTO country(country,continent) VALUES ('Iran',2);
INSERT INTO country(country,continent) VALUES ('Iraq',2);
INSERT INTO country(country,continent) VALUES ('Ireland',1);
INSERT INTO country(country,continent) VALUES ('Israel',2);
INSERT INTO country(country,continent) VALUES ('Italy',1);
INSERT INTO country(country,continent) VALUES ('Ivory Coast',3);
INSERT INTO country(country,continent) VALUES ('Jamaica',5);
INSERT INTO country(country,continent) VALUES ('Japan',2);
INSERT INTO country(country,continent) VALUES ('Jordan',2);
INSERT INTO country(country,continent) VALUES ('Kazakhstan',2);
INSERT INTO country(country,continent) VALUES ('Kenya',3);
INSERT INTO country(country,continent) VALUES ('Kiribati',4);
INSERT INTO country(country,continent) VALUES ('Kuwait',2);
INSERT INTO country(country,continent) VALUES ('Kyrgyzstan',2);
INSERT INTO country(country,continent) VALUES ('Laos',2);
INSERT INTO country(country,continent) VALUES ('Latvia',1);
INSERT INTO country(country,continent) VALUES ('Lebanon',2);
INSERT INTO country(country,continent) VALUES ('Lesotho',3);
INSERT INTO country(country,continent) VALUES ('Liberia',3);
INSERT INTO country(country,continent) VALUES ('Libyan Arab Jamahiriya',3);
INSERT INTO country(country,continent) VALUES ('Liechtenstein',1);
INSERT INTO country(country,continent) VALUES ('Lithuania',1);
INSERT INTO country(country,continent) VALUES ('Luxembourg',1);
INSERT INTO country(country,continent) VALUES ('Macao',2);
INSERT INTO country(country,continent) VALUES ('North Macedonia',1);
INSERT INTO country(country,continent) VALUES ('Madagascar',3);
INSERT INTO country(country,continent) VALUES ('Malawi',3);
INSERT INTO country(country,continent) VALUES ('Malaysia',2);
INSERT INTO country(country,continent) VALUES ('Maldives',2);
INSERT INTO country(country,continent) VALUES ('Mali',3);
INSERT INTO country(country,continent) VALUES ('Malta',1);
INSERT INTO country(country,continent) VALUES ('Marshall Islands',4);
INSERT INTO country(country,continent) VALUES ('Martinique',5);
INSERT INTO country(country,continent) VALUES ('Mauritania',3);
INSERT INTO country(country,continent) VALUES ('Mauritius',3);
INSERT INTO country(country,continent) VALUES ('Mayotte',3);
INSERT INTO country(country,continent) VALUES ('Mexico',5);
INSERT INTO country(country,continent) VALUES ('Micronesia, Federated States of',4);
INSERT INTO country(country,continent) VALUES ('Moldova',1);
INSERT INTO country(country,continent) VALUES ('Monaco',1);
INSERT INTO country(country,continent) VALUES ('Mongolia',2);
INSERT INTO country(country,continent) VALUES ('Montserrat',5);
INSERT INTO country(country,continent) VALUES ('Morocco',3);
INSERT INTO country(country,continent) VALUES ('Mozambique',3);
INSERT INTO country(country,continent) VALUES ('Myanmar',2);
INSERT INTO country(country,continent) VALUES ('Namibia',3);
INSERT INTO country(country,continent) VALUES ('Nauru',4);
INSERT INTO country(country,continent) VALUES ('Nepal',2);
INSERT INTO country(country,continent) VALUES ('Netherlands',1);
INSERT INTO country(country,continent) VALUES ('Netherlands Antilles',5);
INSERT INTO country(country,continent) VALUES ('New Caledonia',4);
INSERT INTO country(country,continent) VALUES ('New Zealand',4);
INSERT INTO country(country,continent) VALUES ('Nicaragua',5);
INSERT INTO country(country,continent) VALUES ('Niger',3);
INSERT INTO country(country,continent) VALUES ('Nigeria',3);
INSERT INTO country(country,continent) VALUES ('Niue',4);
INSERT INTO country(country,continent) VALUES ('Norfolk Island',4);
INSERT INTO country(country,continent) VALUES ('North Korea',2);
INSERT INTO country(country,continent) VALUES ('Northern Ireland',1);
INSERT INTO country(country,continent) VALUES ('Northern Mariana Islands',4);
INSERT INTO country(country,continent) VALUES ('Norway',1);
INSERT INTO country(country,continent) VALUES ('Oman',2);
INSERT INTO country(country,continent) VALUES ('Pakistan',2);
INSERT INTO country(country,continent) VALUES ('Palau',4);
INSERT INTO country(country,continent) VALUES ('Palestine',2);
INSERT INTO country(country,continent) VALUES ('Panama',5);
INSERT INTO country(country,continent) VALUES ('Papua New Guinea',4);
INSERT INTO country(country,continent) VALUES ('Paraguay',6);
INSERT INTO country(country,continent) VALUES ('Peru',6);
INSERT INTO country(country,continent) VALUES ('Philippines',2);
INSERT INTO country(country,continent) VALUES ('Pitcairn',4);
INSERT INTO country(country,continent) VALUES ('Poland',1);
INSERT INTO country(country,continent) VALUES ('Portugal',1);
INSERT INTO country(country,continent) VALUES ('Puerto Rico',5);
INSERT INTO country(country,continent) VALUES ('Qatar',2);
INSERT INTO country(country,continent) VALUES ('Reunion',3);
INSERT INTO country(country,continent) VALUES ('Romania',1);
INSERT INTO country(country,continent) VALUES ('Russian Federation',1);
INSERT INTO country(country,continent) VALUES ('Rwanda',3);
INSERT INTO country(country,continent) VALUES ('Saint Helena',3);
INSERT INTO country(country,continent) VALUES ('Saint Kitts and Nevis',5);
INSERT INTO country(country,continent) VALUES ('Saint Lucia',5);
INSERT INTO country(country,continent) VALUES ('Saint Pierre and Miquelon',5);
INSERT INTO country(country,continent) VALUES ('Saint Vincent and the Grenadines',5);
INSERT INTO country(country,continent) VALUES ('Samoa',4);
INSERT INTO country(country,continent) VALUES ('San Marino',1);
INSERT INTO country(country,continent) VALUES ('Sao Tome and Principe',3);
INSERT INTO country(country,continent) VALUES ('Saudi Arabia',2);
INSERT INTO country(country,continent) VALUES ('Scotland',1);
INSERT INTO country(country,continent) VALUES ('Senegal',3);
INSERT INTO country(country,continent) VALUES ('Seychelles',3);
INSERT INTO country(country,continent) VALUES ('Sierra Leone',3);
INSERT INTO country(country,continent) VALUES ('Singapore',2);
INSERT INTO country(country,continent) VALUES ('Slovakia',1);
INSERT INTO country(country,continent) VALUES ('Slovenia',1);
INSERT INTO country(country,continent) VALUES ('Solomon Islands',4);
INSERT INTO country(country,continent) VALUES ('Somalia',3);
INSERT INTO country(country,continent) VALUES ('South Africa',3);
INSERT INTO country(country,continent) VALUES ('South Georgia and the South Sandwich Islands',7);
INSERT INTO country(country,continent) VALUES ('South Korea',2);
INSERT INTO country(country,continent) VALUES ('South Sudan',3);
INSERT INTO country(country,continent) VALUES ('Spain',1);
INSERT INTO country(country,continent) VALUES ('Sri Lanka',2);
INSERT INTO country(country,continent) VALUES ('Sudan',3);
INSERT INTO country(country,continent) VALUES ('Suriname',6);
INSERT INTO country(country,continent) VALUES ('Svalbard and Jan Mayen',1);
INSERT INTO country(country,continent) VALUES ('Swaziland',3);
INSERT INTO country(country,continent) VALUES ('Sweden',1);
INSERT INTO country(country,continent) VALUES ('Switzerland',1);
INSERT INTO country(country,continent) VALUES ('Syria',2);
INSERT INTO country(country,continent) VALUES ('Tajikistan',2);
INSERT INTO country(country,continent) VALUES ('Tanzania',3);
INSERT INTO country(country,continent) VALUES ('Thailand',2);
INSERT INTO country(country,continent) VALUES ('The Democratic Republic of Congo',3);
INSERT INTO country(country,continent) VALUES ('Togo',3);
INSERT INTO country(country,continent) VALUES ('Tokelau',4);
INSERT INTO country(country,continent) VALUES ('Tonga',4);
INSERT INTO country(country,continent) VALUES ('Trinidad and Tobago',5);
INSERT INTO country(country,continent) VALUES ('Tunisia',3);
INSERT INTO country(country,continent) VALUES ('Turkey',2);
INSERT INTO country(country,continent) VALUES ('Turkmenistan',2);
INSERT INTO country(country,continent) VALUES ('Turks and Caicos Islands',5);
INSERT INTO country(country,continent) VALUES ('Tuvalu',4);
INSERT INTO country(country,continent) VALUES ('Uganda',3);
INSERT INTO country(country,continent) VALUES ('Ukraine',1);
INSERT INTO country(country,continent) VALUES ('United Arab Emirates',2);
INSERT INTO country(country,continent) VALUES ('United Kingdom',1);
INSERT INTO country(country,continent) VALUES ('United States',5);
INSERT INTO country(country,continent) VALUES ('United States Minor Outlying Islands',4);
INSERT INTO country(country,continent) VALUES ('Uruguay',6);
INSERT INTO country(country,continent) VALUES ('Uzbekistan',2);
INSERT INTO country(country,continent) VALUES ('Vanuatu',4);
INSERT INTO country(country,continent) VALUES ('Venezuela',6);
INSERT INTO country(country,continent) VALUES ('Vietnam',2);
INSERT INTO country(country,continent) VALUES ('Virgin Islands, British',5);
INSERT INTO country(country,continent) VALUES ('Virgin Islands, U.S.',5);
INSERT INTO country(country,continent) VALUES ('Wales',1);
INSERT INTO country(country,continent) VALUES ('Wallis and Futuna',4);
INSERT INTO country(country,continent) VALUES ('Western Sahara',3);
INSERT INTO country(country,continent) VALUES ('Yemen',2);
INSERT INTO country(country,continent) VALUES ('Yugoslavia',1);
INSERT INTO country(country,continent) VALUES ('Zambia',3);
INSERT INTO country(country,continent) VALUES ('Zimbabwe',3);